### ISSUE TITLE
请问这个模型是否能支持流式f0预测？

### ISSUE THREAD

**Issue by Jackiexiao** [CNChTu/FCPE#4]
你好，请问这个模型是否能支持流式f0预测？如果不支持，今后是否有计划实现？

**Comment by CNChTu** [comment]
支持。但模型有上下文建模，与训练时保持同一片段长度可能性能更优

**Comment by Jackiexiao** [comment]
感谢

**Comment by ylzz1997** [comment]
目前支持的是带上下文的预测，实际上可以只看上文的causal预测也没问题

**Comment by liziru** [comment]
> 支持。但模型有上下文建模，与训练时保持同一片段长度可能性能更优

计算量上，和rmvpe哪个计算量小一点？

**Comment by Jackiexiao** [comment]
这个小一点
